### ISSUE TITLE
Upgrading to Selenide 4.14.2 causes Compilation Error

### ISSUE THREAD

**Issue by ProNationWolf** [codeborne/selenide-appium#13]
Hello, 

Please check  ScreenObject.java and SelenideAppiumFieldDecorator.java 

**ScreenObject.java**

    /**
     * Initialize a Page Object fields annotated with @FindBy, @AndroidFindBy, @iOSFindBy etc.
     */
    public static <PageObjectClass, T extends PageObjectClass> PageObjectClass screen(T pageObject) {
        SelenidePageFactory.initElements(new SelenideAppiumFieldDecorator(getWebDriver()), pageObject);
        return pageObject;
    }

**Error** : Cannot make a static reference to the non-static method initElements(FieldDecorator, Object) from the type SelenidePageFactory

**SelenideAppiumFieldDecorator**

    private ElementsContainer initElementsContainer(Class<?> type, SelenideElement self) throws Exception {
        Constructor<?> constructor = type.getDeclaredConstructor();
        constructor.setAccessible(true);
        ElementsContainer result = (ElementsContainer) constructor.newInstance();
        PageFactory.initElements(new SelenideFieldDecorator(self), result);
        result.setSelf(self);
        return result;
    }
 
**Error : The constructor SelenideFieldDecorator(SelenideElement) is undefined**

**Comment by asolntsev** [comment]
@ProNationWolf Thank you for reporting! Fixed in master branch.
